services:
  mysql:
    image: mysql:8.0.43
    container_name: mysql-server
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my-db
    volumes:
      - ./data:/var/lib/mysql/
    networks:
      - mysql
    ports:
      - "3306:3306"
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci

networks:
  mysql:
    driver: bridge
