# password
; requirepass xxx

# Enable RDB persistence (snapshotting)
save 900 1    # Save after 900 sec (15 min) if at least 1 key changed
save 300 10   # Save after 300 sec (5 min) if at least 10 keys changed
save 60 10000 # Save after 60 sec if at least 10000 keys changed
rdbcompression yes  # Enable RDB compression
dbfilename dump.rdb # Name of the RDB file

# Enable AOF persistence (append-only file)
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec  # Sync AOF file every second

# Data directory (matches volume mapping in docker-compose)
dir /data